#include "rubichart.h"

void RubiChart::_bind_methods() {
    BIND_CONSTANT(MAX_LANE_COUNT);

    BIND_ENUM_CONSTANT(QUANT_VALUE_4TH);
    BIND_ENUM_CONSTANT(QUANT_VALUE_8TH);
    BIND_ENUM_CONSTANT(QUANT_VALUE_12TH);
    BIND_ENUM_CONSTANT(QUANT_VALUE_16TH);
    BIND_ENUM_CONSTANT(QUANT_VALUE_24ND);
    BIND_ENUM_CONSTANT(QUANT_VALUE_32ND);
    BIND_ENUM_CONSTANT(QUANT_VALUE_48TH);
    BIND_ENUM_CONSTANT(QUANT_VALUE_64TH);
    BIND_ENUM_CONSTANT(QUANT_VALUE_192ND);
}