#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")
Import("env_modules")

env_rubicon_core = env_modules.Clone()

env_rubicon_core.add_source_files(env.modules_sources, "*.cpp")
env_rubicon_core.add_source_files(env.modules_sources, "./chart/*.cpp")
env_rubicon_core.add_source_files(env.modules_sources, "./meta/*.cpp")